# project depedent section to be modified by user
SRCFILE	= /home/syshen/compsyn_ips/xgxs_err/src/XGXSPCS/XGXSSYNTH_ENC_8B10B.v
TOPMOD = XGXSSYNTH_ENC_8B10B
DCINCPATH = /home/syshen/compsyn_ips/xgxs_err/src/XGXSPCS
INPUT = -Input encode_data_in -Input konstant
OUTPUT = -Output encode_data_out

include ../../../vp/scr/Makefile.in
