# project depedent section to be modified by user
SRCFILE	= ../src/Huffman_alphabet_5.v
TOPMOD = Huffman_alphabet_5
DCINCPATH = ../src
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input in_0 -Input in_1 -Input in_2 -Input in_3 -Input in_4
OUTPUT = -Output carestate -Output out

include ../../../vp/scr/Makefile.in
