# project depedent section to be modified by user
SRCFILE	= ../src/verilog/filelist.v
TOPMOD = PCIEXP_TX
DCINCPATH = ../src/verilog
INPUT = -Input TXDATA -Input TXDATAK
OUTPUT = -Output HSS_TXD 

include ../../../vp/scr/Makefile.in
