# project depedent section to be modified by user
# 8 reg version
# SRCFILE	= ../src/CC_3noise_balanced.v
# TOPMOD = Convolutional_Code_3
# DCINCPATH = ../src
# INPUT = -Input in 
# OUTPUT = -Output out1 -Output out2

# 6 reg
# seems to be the correct one
# non uniq at all
 SRCFILE	= ../src/CC_3noise_a_balanced.v
 TOPMOD = Convolutional_Code_3
 DCINCPATH = ../src
 INPUT = -Input in 
 OUTPUT = -Output out1 -Output out2 -Output decosy

# 6 reg
# non uniq at all
#SRCFILE	= ../src/CC_3temp_balanced.v
#TOPMOD = Convolutional_Code_3
#DCINCPATH = ../src
#INPUT = -Input in -Input noise0 -Input noise1
#OUTPUT = -Output out1 -Output out2 -Output decosy

include ../../../vp/scr/Makefile.in
