# project depedent section to be modified by user
SRCFILE	= ../src/Huffman_skew_6.v
TOPMOD = Huffman_skew_6
DCINCPATH = ../src
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input in_0 -Input in_1 -Input in_2 -Input in_3 -Input in_4 -Input in_5
OUTPUT = -Output carestate -Output out

include ../../../vp/scr/Makefile.in
