# project depedent section to be modified by user
#SRCFILE	= ../src/CC_4noise_a_balanced.v
SRCFILE	= ../src/CC_4noise_a_balanced.v
TOPMOD = Convolutional_Code_4
DCINCPATH = ../src
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input in 
#OUTPUT = -Output out1 -Output out2 -Output decosy
OUTPUT = -Output out1 -Output out2

include ../../../vp/scr/Makefile.in
