# project depedent section to be modified by user
# the one with 6 regs, no the one use in TCAD12
# SRCFILE	= ../src/hamming7_no_dec_balanced.v
# TOPMOD = hamming
# DCINCPATH = ../src
# INPUT = -Input in1 -Input in2 -Input in3 -Input in4
# OUTPUT = -Output out2 -Output out3 -Output out4 -Output out5 -Output out6 -Output out7

# the one with 3 reg
#SRCFILE	= ../src/hamming7_balanced.v
SRCFILE	= ../src/hamming7.v
TOPMOD = hamming7
DCINCPATH = ../src
INPUT = -Input in1 -Input in2 -Input in3 -Input in4
OUTPUT = -Output out1 -Output out2 -Output out3 -Output out4 -Output out5 -Output out6 -Output out7

include ../../../vp/scr/Makefile.in
