# project depedent section to be modified by user
SRCFILE	= ../src/LFSR_12_6_4.v
TOPMOD = LFSR_12_6_4
DCINCPATH = ../src
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input in
OUTPUT = -Output out

include ../../../vp/scr/Makefile.in
