open Printf
open Unix
open Misc
open Typedef

let rec print_source_text fc source_text = begin
	fprintf fc "//generated by checker at %s\n" (get_time_string );
	List.iter (print_description fc) source_text
end
and print_description fc description = begin
	match description with
	T_description__module_declaration(module_declaration) -> begin
		print_module_declaration fc module_declaration
	end
	| _ -> assert false
end
and print_module_declaration fc module_declaration = begin
	match module_declaration with
	T_module_declaration__1(
		attribute_instance_list,
		module_identifier,
		module_parameter_port_list_opt,
		list_of_ports,
		module_item_list
	) -> begin
		fprintf fc "module  %s\n" (get_identifier_string module_identifier);
	end
end
