# project depedent section to be modified by user
SRCFILE	= ../src/LFSR_26_6_2.v
TOPMOD = LFSR_26_6_2
DCINCPATH = ../src
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input in
OUTPUT = -Output out

include ../../../vp/scr/Makefile.in
