# project depedent section to be modified by user
SRCFILE	= /home/syshen/compsyn_ips/pcie_noass/src/verilog/filelist.v
TOPMOD = PCIEXP_TX
DCINCPATH = /home/syshen/compsyn_ips/pcie_noass/src/verilog
INPUT = -Input TXDATA -Input TXDATAK
OUTPUT = -Output HSS_TXD 

include ../../../vp/scr/Makefile.in
