# project depedent section to be modified by user
SRCFILE	= ../src/muxencoder.v
TOPMOD = muxencoder
DCINCPATH = ../src
INPUT = -Input in_data 
OUTPUT = -Output out_data 

include ../../../vp/scr/Makefile.in
