# project depedent section to be modified by user
SRCFILE	= ../src/muxencoder.v
TOPMOD = muxencoder
DCINCPATH = ../src
INPUT = -Input in_data -Input  in_datavalid
OUTPUT = -Output out_data -Output  out_datavalid

include ../../../vp/scr/Makefile.in
