
`define PCIEXPHYIF_PCIEXPHYIF_MODNAME        PCIEXPHYIF16
`define PCIEXPHYIF_RST_MODNAME               PCIEXP_RSTX16
`define PCIEXPHYIF_CNTL_MODNAME              PCIEXP_CNTLX16

//`define PCIEXPHYIF_LINKWIDTH_X4
// `define PCIEXPHYIF_LINKWIDTH_X8
 `define PCIEXPHYIF_LINKWIDTH_X16








`ifdef PCIEXPHYIF_LINKWIDTH_X4
  `define PCIEXPHYIF_BUSWIDTH  3
`endif
`ifdef PCIEXPHYIF_LINKWIDTH_X8
  `define PCIEXPHYIF_BUSWIDTH  7
`endif
`ifdef PCIEXPHYIF_LINKWIDTH_X16
  `define PCIEXPHYIF_BUSWIDTH  15
`endif


