# project depedent section to be modified by user
# the one with 6 regs not the TCAD12
# SRCFILE	= ../src/hamming15_no_dec_balanced.v
# TOPMOD = hamming
# DCINCPATH = ../src
# #INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
# INPUT = -Input in1 -Input in2 -Input in3 -Input in4 -Input in5 -Input in6 -Input in7 -Input in8 -Input in9 -Input in10 -Input in11
# OUTPUT = -Output out2 -Output out3 -Output out4 -Output out5 -Output out6 -Output out7 -Output out8 -Output out9 -Output out10 -Output out11 -Output out12 -Output out13 -Output out14 -Output out15

# the one with 4 regs
SRCFILE	= ../src/hamming15.v
TOPMOD = hamming15
DCINCPATH = ../src
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input in1 -Input in2 -Input in3 -Input in4 -Input in5 -Input in6 -Input in7 -Input in8 -Input in9 -Input in10 -Input in11
OUTPUT = -Output out1  -Output out2 -Output out3 -Output out4 -Output out5 -Output out6 -Output out7 -Output out8 -Output out9 -Output out10 -Output out11 -Output out12 -Output out13 -Output out14 -Output out15

include ../../../vp/scr/Makefile.in
