# project depedent section to be modified by user
SRCFILE	= ../src/Huffman_random_9_1.v
TOPMOD = Huffman_random_9
DCINCPATH = ../src
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input in_0 -Input in_1 -Input in_2 -Input in_3 -Input in_4  -Input in_5 -Input in_6 -Input in_7 -Input in_8
OUTPUT = -Output carestate -Output out

include ../../../vp/scr/Makefile.in
