# project depedent section to be modified by user
SRCFILE	= ../src/fl_syn.v
TOPMOD = XFIPCS_64B66B_ENC
DCINCPATH = ../src/XFIPCS
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN
OUTPUT = -Output ENCODER_DATA_OUT 

DECSRCFILE	= ../src/XFIPCS/XFIPCS_64B66B_DEC.v
DECTOPMOD = XFIPCS_64B66B_DEC



include ../../../vp/scr/Makefile.in
