# project depedent section to be modified by user
SRCFILE	= ../src/filelist_syn.v
TOPMOD = ge_1000baseX_tx
DCINCPATH = ../src/rtl/verilog
INPUT = -Input gmii_tx_en_in -Input gmii_txd_in 
OUTPUT = -Output tbi_txd -Output transmitting -Output gmii_col -Output tx_frame_pulse

include ../../../vp/scr/Makefile.in
