# project depedent section to be modified by user
SRCFILE	= ../src/buffer.v
TOPMOD = buffer
DCINCPATH = ../src/
INPUT = -Input in
OUTPUT = -Output out
RESET_CONDITION = "reset==1'b1"

#DECSRCFILE = ../src/verilog/PCIEXP_108DEC.v
#DECTOPMOD = PCIEXP_108DEC

include ../../../vp/scr/Makefile.in
