# project depedent section to be modified by user
SRCFILE	= ../src/scrambler.v
TOPMOD = scrambler
DCINCPATH = .
INPUT = -Input data_66b_tpg
OUTPUT = -Output data_scrambled

include ../../../vp/scr/Makefile.in
