# project depedent section to be modified by user
SRCFILE	= /home/syshen/compsyn_ips/xfi_relational/src/fl_syn.v
TOPMOD = XFIPCS_TX_PCS
DCINCPATH = /home/syshen/compsyn_ips/xfi_relational/src/XFIPCS
INPUT = -Input tx_fifo_pop_pre -Input txc_xfi -Input txd_xfi    
#INPUT =   -Input tx_fifo_pop_pre   -Input  txc_xfi
OUTPUT = -Output tx_data_out  -Output tx_fifo_pop_2  -Output  tx_mode  -Output t_type_li   -Output  TXxQUIET  -Output  TXxREFRESH

include ../../../vp/scr/Makefile.in
