# project depedent section to be modified by user
SRCFILE	= ../src/CC_14.v
TOPMOD = Convolutional_Code_14
DCINCPATH = ../src
#INPUT = -Input ENCODER_DATA_IN -Input ENCODER_CONTROL_IN -Input DATA_VALID
INPUT = -Input in 
OUTPUT = -Output out1 -Output out2

include ../../../vp/scr/Makefile.in
